### ISSUE TITLE
Jupyter lab3.0

### ISSUE THREAD

**Issue by XDWang97** [dracula/JupyterLab#8]
Hi, everyone

When I installed Dracula to Jupyter lab,problem occured
`The extension "@karosc/jupyterlab_dracula" does not yet support the current version of JupyterLab.`

My jupyter lab version is 3.0.0

Does Dracula not support jupyter lab version **3.x**?

**Comment by zenorocha** [comment]
@karosc can you take a look on this one?

**Comment by karosc** [comment]
I've been meaning to migrate the theme to 3.0. I already did for my light colored tomorrow theme. Should be able to take care of this tomorrow night (no pun intended), and once updated it will be installable by pip rather than npm.

**Comment by 7kemZmani** [comment]
@karosc how can we install extensions using `pip`? I know how to use the extensions manager and also `jupyter labextension install <some-extension>` but not the `pip` way. Installing extensions using pip is mentioned here https://jupyterlab.readthedocs.io/en/stable/user/extensions.html but with no example.

**Comment by karosc** [comment]
After jupyterlab 3.0 was released, extensions can now be published either on npm or pip. 

If it's publish on npm, you install with `jupyter lab extension install`

If it's published on pip, you can install with `pip install`

Publishing on pip is beneficial because you won't need to rebuild jupyter lab after install or uninstall, the extension is prebuilt.

Checkout my [JLTomorrow](https://github.com/karosc/JLTomorrow) theme that is published on pip.

**Comment by karosc** [comment]
Should be able to install on JL 3.0 now with `pip install JLDracula`

**Comment by XDWang97** [comment]
I got it, that's cool,very very thanks.
